CREATE TABLE IF NOT EXISTS vehicle
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY not null,
    user_id BIGINT,
    brand VARCHAR(255) not null,
    model VARCHAR(255) not null,
    number_of_seats TINYINT,
    production_year SMALLINT,
    top_speed SMALLINT,
    type VARCHAR(255) not null,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    created_on timestamp(6) not null default (CURRENT_TIMESTAMP(6)),
    updated_on timestamp(6) not null default (CURRENT_TIMESTAMP(6)),
    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES app_user(id)
)