CREATE TABLE IF NOT EXISTS equipment
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY not null,
    name VARCHAR(255),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    created_on timestamp(6) not null default (CURRENT_TIMESTAMP(6)),
    updated_on timestamp(6) not null default (CURRENT_TIMESTAMP(6)),
    PRIMARY KEY(id)
)